export interface Note {
  id: string;
  pitch: string; // e.g. "C4", "F#3"
  midi: number;  // 0-127
  startBeat: number; // in beats (0, 0.5, 1, 1.5, etc.)
  duration: number;  // in beats
  velocity: number;  // 0-127
}

export type InstrumentType =
  | 'acoustic_grand_piano'
  | 'electric_piano'
  | 'acoustic_guitar'
  | 'electric_guitar'
  | 'synth_lead'
  | 'synth_pad'
  | 'electric_bass'
  | 'sub_bass_808'
  | 'drum_kit'
  | 'strings_ensemble'
  | 'brass_section'
  | 'flute_sax'
  | 'vocal_choir';

export interface Track {
  id: string;
  name: string;
  instrument: InstrumentType;
  channel: number;
  volume: number; // 0 to 1
  pan: number;    // -1 to 1
  muted: boolean;
  solo: boolean;
  color: string;
  notes: Note[];
}

export interface LyricLine {
  section: string; // "Intro", "Verso 1", "Refrão", "Ponte", "Outro"
  text: string;
  timestamp?: number; // in seconds
  startBeat?: number; // in beats (for karaoke highlight)
}

export interface SongProject {
  id: string;
  title: string;
  prompt: string;
  style: string;
  mood: string;
  bpm: number;
  key: string;
  timeSignature: string; // e.g. "4/4", "3/4"
  createdAt: number;
  updatedAt: number;
  tracks: Track[];
  lyrics: LyricLine[];
  audioBase64?: string; // Generated by Lyria or rendered WAV
  audioMimeType?: string;
  audioUrl?: string; // Real AI-rendered audio (Replicate etc.) — played directly
  durationSeconds: number;
  generationModel: string;
  isFavorite?: boolean;
  tags: string[];
  coverArtGradient?: string;
}

export interface BackupSnapshot {
  id: string;
  timestamp: number;
  label: string;
  projectCount: number;
  projects: SongProject[];
}

export interface CloudSyncPayload {
  syncCode: string;
  updatedAt: number;
  projects: SongProject[];
  snapshots: BackupSnapshot[];
}

export interface MusicGenerationRequest {
  prompt: string;
  style: string;
  mood: string;
  bpm?: number;
  key?: string;
  instruments?: string[];
  modelType: 'lyria-clip' | 'lyria-pro' | 'gemini-flash' | 'local';
  durationSeconds?: number;
  imageBase64?: string;
  imageMimeType?: string;
}
